sudo: required
services:
  - docker
language: bash
script:
  # Build image
  - docker build -t christronyxyocum/docker-plpp .
  # Test image
  - docker run christronyxyocum/docker-plpp nginx -v
after_success:
  # Push image
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" ${DOCKER_REGISTRY}
  - docker push tronyx/docker-plpp
